# Generated by Django 4.2.4 on 2023-10-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='story/audios'),
        ),
    ]
