# Generated by Django 4.2.4 on 2023-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
