# Generated by Django 4.2.4 on 2023-11-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numper_of_lesson', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('leavel', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('quiz', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Lesson_Quiz', to='tests.quiz')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='People_Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'People_Ask',
                'verbose_name_plural': 'People_Asks',
            },
        ),
        migrations.CreateModel(
            name='Said_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=100, null=True)),
                ('said_description', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lesson')),
            ],
            options={
                'verbose_name': 'Said_question',
                'verbose_name_plural': 'Said_questions',
            },
        ),
        migrations.CreateModel(
            name='Lesson_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_word_id', models.IntegerField(blank=True, default=99, null=True)),
                ('word_AR', models.CharField(blank=True, max_length=50, null=True)),
                ('word_RU', models.CharField(blank=True, max_length=50, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lesson')),
            ],
            options={
                'verbose_name': 'Lesson_words',
                'verbose_name_plural': 'Lesson_wordss',
            },
        ),
    ]
