# Generated by Django 4.2.4 on 2023-11-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_words',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
