# Generated by Django 4.2.4 on 2023-09-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_said_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_AR', models.CharField(max_length=50)),
                ('word_RU', models.CharField(max_length=50)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lesson')),
            ],
            options={
                'verbose_name': 'Lesson_words',
                'verbose_name_plural': 'Lesson_wordss',
            },
        ),
    ]
