# Generated by Django 4.2.4 on 2023-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_lesson_words_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='active',
            field=models.BooleanField(blank=True, default='доступен', null=True),
        ),
    ]
