# Generated by Django 4.2.4 on 2023-09-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lesson_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_words',
            name='lesson_word_id',
            field=models.IntegerField(default=99),
        ),
    ]
