# Generated by Django 4.2.4 on 2023-10-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_discrption'),
        ('home', '0005_alter_lesson_active_alter_lesson_description_and_more'),
    ]

