# Generated by Django 4.2.4 on 2023-10-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_lesson_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'People_Ask',
                'verbose_name_plural': 'People_Asks',
            },
        ),
    ]
