# Generated by Django 4.2.4 on 2023-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='discrption',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
