# Generated by Django 4.2.4 on 2023-10-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_discrption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_word_id', models.IntegerField(blank=True, default=99, null=True)),
                ('word_AR', models.CharField(blank=True, max_length=50, null=True)),
                ('word_RU', models.CharField(blank=True, max_length=50, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.quiz')),
            ],
            options={
                'verbose_name': 'Quiz_words',
                'verbose_name_plural': 'Quiz_wordss',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Said_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=100, null=True)),
                ('said_description', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.quiz')),
            ],
            options={
                'verbose_name': 'Quiz_Said_question',
                'verbose_name_plural': 'Quiz_Said_questions',
            },
        ),
    ]
